spring.application.name=authenticus
server.port=8080

# #H2 database configuration


# # Enable H2 console in the browser
# spring.h2.console.enabled=true

# # Auto-generate the database schema based on the entities
# spring.jpa.hibernate.ddl-auto=update
# spring.jpa.open-in-view=false


